#!/usr/bin/env bash

set -ex

die() {
    echo "$@"
    exit 1
}

require() {
    type -p $1 || die Missing prerequisite: $1
}

require git
require pip

type -p dir2pi || pip install pip2pi

top="$(git rev-parse --show-toplevel 2>/dev/null)" ||
    top="$(cd "$(dirname "$0")" && pwd)"

cd "$top"

stashed=$(git stash)
git switch gh-pages
git pull
# move `index.html` out of the way to avoid `dir2pi` choking
rm index.html
dir2pi .
# restore `index.html`
git restore index.html
git add .
git commit -am Update\ Pages
git push
git switch main
[ "$stashed" = "No local changes to save" ] || git stash pop
