#!/usr/bin/env bash

set -ex

die() {
    echo "$@"
    exit 1
}

require() {
    type -p $1 || die Missing prerequisite: $1
}

require git
require pip

type -p dir2pi || pip install pip2pi

top="$(git rev-parse --show-toplevel 2>/dev/null)" ||
    top="$(cd "$(dirname "$0")" && pwd)"

cd "$top"

stashed=$(git stash)
cp -va wheels wheels.
git switch gh-pages
dir2pi -S wheels.
cp -va wheels./simple/* .
rm -fr wheels.
git add .
git commit -am Update\ Pages
git push
git switch main
[ "$stashed" = "No local changes to save" ] || git stash pop
